### ISSUE TITLE
[TODO] 2주차 - 대욱

### ISSUE THREAD

**Issue by wattt3** [OwO-CR/OWOCR#10]
# Uk's TODO list

- [ ] 프로그래머스 강의
- [ ] 시작하세요 도커 쿠버네티스 읽기 / 쿠버네티스 인 액션 책 구매
- [ ] 인프런 kaggle 강의
- [ ] 코딩테스트 백준 문자열 3~4문제
- [ ] tabnet 논문 read
