### ISSUE TITLE
[TODO] 2주차 - 창수

### ISSUE THREAD

**Issue by cieske** [OwO-CR/OWOCR#11]
- [ ] meta-tail2vec, tail-GNN 읽고 ppt
    - [ ] 목요일 발표 2개

- [ ] Graph+항원항체 반응 논문 서베이(Nature'20 + a)

- [ ] Vision & Recsys 주제 맞는 baseline 논문 서베이

- [ ] 실험
    - [ ] Item-uniform resampling 
    - [ ] Long-tail resampling -> Reduce # of parameter
        - [ ] 이거 했던 기존 논문이 있나?
    - [ ] Gating 관련 아이디어들
        - [ ] Small d*d mapping function
        - [ ] What else?
