### ISSUE TITLE
[TODO] 2주차 - 대현

### ISSUE THREAD

**Issue by GiDaeHyeon** [OwO-CR/OWOCR#12]
- [ ] IT 엔지니어를 위한 네트워크 입문
    - [ ] 1.1 네트워크 구성도 알아보기
    - [ ] 1.2 프로토콜
    - [ ] 1.3 OSI 7계층과 TCP/IP
    - [ ] 1.4 OSI 7계층별 알아보기
    - [ ] 1.5 인캡슐레이션과 디캡슐레이션
- [ ] 파이썬 코딩의 기술
    - [ ] 1. 사용 중인 파이썬의 버전을 알아두라
    - [ ] 2. PEP 8 스타일 가이드를 따르라
    - [ ] 3. bytes와 str의 차이를 알아두라
    - [ ] 4. f-문자열을 통한 인터폴레이션을 활용하라
    - [ ] 5. 복잡한 식을 쓰는 대신 도우미 함수를 작성하라
- [ ] 엘라스틱 스택 개발부터 운영까지
    - [ ] 1.3 엘라스틱 스택의 구성요소
    - [ ] 1.4 엘라스틱 스택의 용도
    - [ ] 1.5 빅데이터 플랫폼의 일부로 동작하는 엘라스틱 스택
- [ ] 혼자 공부하는 JAVA
    - [ ] 2.1 변수
    - [ ] 2.2 기본 타입
    - [ ] 2.3 타입 변환
    - [ ] 2.4 변수와 시스템 입출력
- [ ] NodeJS 교과서
    - [ ] 3.1 REPL 사용하기
    - [ ] 3.2 js 파일 실행하기
    - [ ] 3.3 모듈로 만들기
    - [ ] 3.4 노드 내장 객체 알아보기
    - [ ] 3.5 노드 내장 모듈 사용하기
    - [ ] 3.6 파일 시스템 접근하기
    - [ ] 3.7 이벤트 이해하기
    - [ ] 3.8 예외 처리하기
