### ISSUE TITLE
1주차 - 용택

### ISSUE THREAD

**Issue by teang1995** [OwO-CR/OWOCR#2]
## TODO's
- [x] collaborative metric learning 리뷰
- [x] collaborative metric learning 구현
- [x] BERT 긍정 부정 모델 BentoML/KubeFlow 적용
    - [x] kcbert from config, pretrained model file
    - [x] 노트북으로 긍/부정 판단 모델 구현
    - [x] 모델 모듈화
    - [ ] BentoML적용 -> tts example 참고
    - [ ] KubeFlow 적용 -> tts example 참고

**Comment by teang1995** [comment]
```
from transformers import AutoModelForMaskedLM, AutoTokenizer
import os

def main():
    bert_path = 'path/to/bert/config/and/modelfile'

    kcbert_mlm = AutoModelForMaskedLM.from_pretrained(bert_path)
    tokenizer = AutoTokenizer.from_pretrained(bert_path)

    print(type(kcbert_mlm))
    print(type(tokenizer))
    print(kcbert_mlm.cls)


if __name__ == "__main__":
    main()
```
각 파일을 지정해줄 필요 없이 config, binary file이 포함된 디렉토리 경로를 `from_pretrained` 함수의 인자로 넣어주면 BERT 모델을 불러올 수 있다. 

### 결과
```
<class 'transformers.models.bert.modeling_bert.BertForMaskedLM'>
<class 'transformers.models.bert.tokenization_bert_fast.BertTokenizerFast'>
BertOnlyMLMHead(
  (predictions): BertLMPredictionHead(
    (transform): BertPredictionHeadTransform(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    )
    (decoder): Linear(in_features=768, out_features=30000, bias=True)
  )
)
```

**Comment by teang1995** [comment]
gluonnlp의 cls_token인식하는 부분에서 문제가 생긴다. 내일은 explore_transform을 통해 `[CLS]`를 처리하는 것부터 시작할 예정!

**Comment by Seonghoon-Yu** [comment]
굳~

**Comment by teang1995** [comment]
와 몸살! 아무 것도 못 했따!

**Comment by Seonghoon-Yu** [comment]
굳~
