### ISSUE TITLE
[TODO] 2주차 - 용택 

### ISSUE THREAD

**Issue by teang1995** [OwO-CR/OWOCR#6]
- [ ] collaborative metric learning 리뷰
- [ ] collaborative metric learning 발표 자료 작성
- [ ] 해석학 1장 공부
- [ ] 회사 일 관련 공부 (추가 예정..)
