### ISSUE TITLE
[TODO] 2주차 - 윤호

### ISSUE THREAD

**Issue by momozzing** [OwO-CR/OWOCR#9]
- [ ] 학교 lab tutorial 마무리
- [ ] NER toy project 진행
- [ ] 매일 토익 공부 -> 산타 매주 풀기 
- [ ] 매일 수학 공부 -> 프로그래머를 위한 확통
